---
# Docker version and packages
docker_compose_version: "v2.20.2"
docker_edition: "ce"
docker_package: "docker-{{ docker_edition }}"

# Docker service configuration
docker_service_state: "started"
docker_service_enabled: true
docker_restart_handler_state: "restarted"

# Docker daemon options
docker_daemon_options: {}

# Users to add to docker group
docker_users:
  - "{{ ansible_user }}"

# Docker repository configuration
docker_yum_repo_url: "https://download.docker.com/linux/centos/8/x86_64/stable/"
docker_yum_repo_gpg_key: "https://download.docker.com/linux/centos/gpg"

# Required packages for Docker installation
docker_required_packages:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - git
  - curl

# Docker Compose installation
docker_compose_path: "/usr/local/bin/docker-compose"
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"

# System update settings
update_system_packages: true
reboot_after_kernel_update: false