---
- name: Test Ansible Connection
  hosts: portfolio_servers
  tasks:
    - name: Check system info
      command: uname -a
      register: system_info
    
    - name: Display system info
      debug:
        msg: "{{ system_info.stdout }}"