---
- name: Update system packages
  yum:
    name: "*"
    state: latest
  become: yes

- name: Install required packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - git
    state: present
  become: yes

- name: Add Docker repository
  yum_repository:
    name: docker-ce
    description: Docker CE Stable repository
    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
  become: yes

- name: Install Docker
  yum:
    name: docker-ce
    state: present
  become: yes
  notify: start docker

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes
  notify: restart docker

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes